# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: "tol/tol-core"
    ref: v1.7.7
    file: "/gitlab/app.yml"

variables:
  APP_NAME: components
  DISABLE_UI_LINT: "true"

build-package-dummy:
  # prevents the accumulation of errors on `yarn build`
  stage: deploy
  image: node:18-alpine
  script:
    - cd components-ui/app/src/tol-ui
    - yarn install
    - yarn build
  except:
    - qa
    - staging
    - production
  needs: []

deploy-package:
  stage: deploy
  image: node:18-alpine
  script:
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - cd components-ui/app/src/tol-ui
    - yarn install
    - yarn build
    - yarn publish
  when: manual
  needs: []
