# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: "tol/tol-core"
    ref: v1.7.0
    file: "/gitlab/app.yml"

variables:
  APP_NAME: components
  DISABLE_UI_LINT: "true"

build-package-dummy:
  # prevents the accumulation of errors on `yarn build`
  stage: deploy
  image: node:18-alpine
  script:
    - cd components-ui/app/src/tol-ui
    - yarn install
    - yarn build
  except:
    - qa
    - staging
    - production
  needs:
    - job: review_app
      optional: true
    - job: build-ui-dev
      optional: true

deploy-package:
  stage: deploy
  image: node:18-alpine
  script:
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - cd components-ui/app/src/tol-ui
    - yarn install
    - yarn build
    - yarn publish
  when: manual
  needs: []

deploy-doc:
  stage: unit test
  image: ${CI_REGISTRY_IMAGE}/${APP_NAME}-ui:$CI_COMMIT_SHA
  before_script:
    - apk add --no-cache python3 py3-pip make gcc musl-dev python3-dev git
    - pip install sphinx sphinx-rtd-theme sphinx-js
    - yarn global add typescript
  script:
    # Adjust these paths as needed for your repo structure
    - cd src/tol-ui/doc  # Assuming your Sphinx docs are in ./docs
    - sphinx-apidoc -o source ../src  # Optional: if you want API docs from .ts files
    - sphinx-build -b html source .public
    - mv .public public
  pages:
    publish: public
  # only:
  #   - production
