# SPDX-FileCopyrightText: 2023 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This is used for local development only
version: '3.1'

services:
  components-db:
    image: elasticsearch:7.17.10
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 9203:9200

  components-api:
    build:
      context: components-api/.
      dockerfile: Dockerfile.dev
    image: components-api
    # force amd64 on M1 MacOS
    # platform: linux/amd64
    environment:
      - DB_URI
      - PARTNER_PORTAL_URL
      - ELIXIR_CLIENT_ID
      - ELIXIR_CLIENT_SECRET
      - ELIXIR_REDIRECT_URI
      - ELIXIR_JWK
      - MAIL_SENDER
      - MAIL_SENDER_NAME
      - MAIL_USERNAME_SMTP
      - MAIL_PASSWORD_SMTP
      - MAIL_HOST
      - MAIL_PORT
      - ENVIRONMENT
      - ELASTIC_URI
      - ELASTIC_USER
      - ELASTIC_PASSWORD
      - ELASTIC_INDEX_PREFIX

    ports:
      - 8088:80
    volumes:
      - './components-api/app/main:/app/main'
      - '../tol-sdk:/packages/tol-sdk:rw'

  components-ui:
    build:
      context: components-ui/.
      dockerfile: Dockerfile.dev
    image: components-ui
    # force amd64 on M1 MacOS
    platform: linux/amd64
    stdin_open: true
    environment:
      - NODE_ENV=development
      - REACT_APP_API_VERSION
    ports:
      - 3010:3000
    volumes:
      - './components-ui/app:/usr/src/app'
      - '/usr/src/app/node_modules'
    
  components-api-test:
    image: components-api
    command: dockerize
        -wait tcp://components-db:5432 -timeout 10s
        bash -c "pytest -v"
    environment:
      - DB_URI
      - PARTNER_PORTAL_URL
      - ELIXIR_CLIENT_ID
      - ELIXIR_CLIENT_SECRET
      - ELIXIR_REDIRECT_URI
      - ELIXIR_JWK
      - MAIL_SENDER
      - MAIL_SENDER_NAME
      - MAIL_USERNAME_SMTP
      - MAIL_PASSWORD_SMTP
      - MAIL_HOST
      - MAIL_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - components-db
      - components-api

  components-ui-test:
    image: components-ui
    command: yarn test
    stdin_open: true
    environment:
      - NODE_ENV=development
    volumes:
      - './components-ui/app:/usr/src/app'
      - '/usr/src/app/node_modules'
  
  components-dbutils:
    image: gitlab-registry.internal.sanger.ac.uk/tol/tol-core/dbutils:1.0.4
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - BACKUP_S3_ACCESS_KEY
      - BACKUP_S3_SECRET_KEY
      - BACKUP_S3_URI
      - BACKUP_S3_BUCKET
      - BACKUP_S3_SECURE
      - RESTORE_FILE_PREFIX
      - FLASK_ENV
      - BACKUP_SCHEDULE
  
  components-alembic:
    image: components-api
    container_name: components-alembic
    restart: always
    environment:
      - DB_URI
    working_dir: /migrations
    volumes:
      - ./components-api/migrations/alembic/versions:/migrations/alembic/versions
