# SPDX-FileCopyrightText: 2023 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This is used for local development only.
FROM em29/tol-web-base-dev:1.0.6

# the app's package.json
COPY ./app/package.json ./

# the tol-ui contents
RUN mkdir -p src
COPY ./app/src/tol-ui ./src/tol-ui

RUN yarn install --dev

COPY ./app/ ./
