"""datasource_to_datasource_instance_fk

Revision ID: b39604352175
Revises: 5698bc61eed0
Create Date: 2025-09-19 14:00:17.250971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'b39604352175'
down_revision = '5698bc61eed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    # Remove `datasource` fields
    op.drop_column("component", "datasource")
    op.drop_column("zone", "datasource")

    # Create new `data_source_instance_id` fields in their places,
    # with foreign keys linking to the DatasourceInstance table
    op.add_column("component", sa.Column("data_source_instance_id", sa.Integer))
    op.create_foreign_key(
        None,  # Use constraint name generated by Alembic
        "component", "data_source_instance",
        ["data_source_instance_id"], ["id"]
    )
    op.add_column("zone", sa.Column("data_source_instance_id", sa.Integer))
    op.create_foreign_key(
        None,  # Use constraint name generated by Alembic
        "zone", "data_source_instance",
        ["data_source_instance_id"], ["id"]
    )

    # Pre-populate `datasource_instance_id` fields with `1` ("tol-production")
    conn.execute(
        text("""
        UPDATE component
        SET data_source_instance_id=1
        """)
    )
    conn.execute(
        text("""
        UPDATE zone
        SET data_source_instance_id=1
        """)
    )


def downgrade() -> None:
    pass
